language: c

before_install: 
 - sudo add-apt-repository ppa:mwild1/ppa -y
 - sudo apt-get update -y
 - sudo apt-get install luajit -y --force-yes
 - sudo apt-get install luarocks -y
 - sudo apt-get install strace -y
 - git submodule update --init --recursive

env:
  - LD_LIBRARY_PATH=./include/buildrump.sh/rump/lib LD_DYNAMIC_WEAK=1

script:
 - luajit test/test.lua
 - mkdir -p ./obj
 - luajit test/linux-constants.lua > ./obj/lc.c && cc -Iinclude/linux-kernel-headers/x86_64/include -o ./obj/lc ./obj/lc.c && ./obj/lc 
 - luajit test/ctest.lua > ./obj/ctest.c && cc -std=c99 ./obj/ctest.c -o ./obj/ctest && ./obj/ctest
 - ./test/globals.sh
 - cd ./include/buildrump.sh && ./buildrump.sh -qq -j16 -V NOSTATICLIB=1 && cd ../..
 - luajit test/test.lua rump

