language: c

before_install: 
 - sudo add-apt-repository ppa:mwild1/ppa -y
 - sudo apt-get update -y
 - sudo apt-get install luajit -y
 - sudo apt-get install luarocks -y
 - sudo apt-get install cvs -y

script: 
 - luajit test/test.lua
 - luajit test/ctest.lua > test/ctest.c && cc -std=c99 test/ctest.c -o test/ctest && ./test/ctest
 - luarocks install --local rockspec/ljsyscall-scm-1.rockspec
 - cd .. && mkdir test && cp -a ljsyscall/test/* test
 - export LUA_PATH="$HOME/.luarocks/share/lua/5.1/?.lua;./?.lua"
 - luajit test/test.lua
 - git clone git://github.com/anttikantee/buildrump.sh.git
 - cd buildrump.sh
 - ./buildrump.sh checkout fullbuild
 - export LD_LIBRARY_PATH="$HOME/buildrump.sh/rump/lib"
 - cd $HOME/ljsyscall
 - luajit examples/rump/fstest.lua


