language: c

before_install:
 - sudo apt-get install libcap-dev -y 
 - sudo add-apt-repository ppa:mwild1/ppa -y
 - sudo apt-get update -y
 - sudo apt-get install luajit -y

script: 
 - luajit test.lua
 - luajit ctest.lua > ctest.c && cc -std=c99 ctest.c -o ctest && ./ctest

